import type { ClothingAttributes } from "@/lib/classify";

/**
 * Seeded into every new account so the closet isn't empty on first login.
 * Not run through AI classification — these are fixed, hand-written entries.
 */
export const SAMPLE_CLOSET: (ClothingAttributes & { imageUrl: string })[] = [
  {
    imageUrl: "/sample/white-shirt.svg",
    category: "top",
    layeringRole: "base_layer",
    warmth: "low",
    color: "white",
    pattern: "solid",
    material: "cotton",
    formality: "smart-casual",
    season: "all-season",
    description: "White fitted shirt",
  },
  {
    imageUrl: "/sample/blue-jeans.svg",
    category: "bottom",
    layeringRole: "bottom",
    warmth: "medium",
    color: "blue",
    pattern: "solid",
    material: "denim",
    formality: "casual",
    season: "all-season",
    description: "Straight-leg blue jeans",
  },
  {
    imageUrl: "/sample/gray-cardigan.svg",
    category: "outerwear",
    layeringRole: "mid_layer",
    warmth: "medium",
    color: "gray",
    pattern: "solid",
    material: "wool blend",
    formality: "smart-casual",
    season: "fall",
    description: "Gray cardigan",
  },
  {
    imageUrl: "/sample/black-jacket.svg",
    category: "outerwear",
    layeringRole: "outer_layer",
    warmth: "high",
    color: "black",
    pattern: "solid",
    material: "cotton twill",
    formality: "casual",
    season: "fall",
    description: "Black casual jacket",
  },
  {
    imageUrl: "/sample/white-sneakers.svg",
    category: "shoes",
    layeringRole: "shoes",
    warmth: "low",
    color: "white",
    pattern: "solid",
    material: "canvas",
    formality: "casual",
    season: "all-season",
    description: "White sneakers",
  },
  {
    imageUrl: "/sample/black-dress.svg",
    category: "dress",
    layeringRole: "one_piece",
    warmth: "low",
    color: "black",
    pattern: "solid",
    material: "jersey",
    formality: "formal",
    season: "all-season",
    description: "Black wrap dress",
  },
  {
    imageUrl: "/sample/brown-belt.svg",
    category: "accessory",
    layeringRole: "accessory",
    warmth: "low",
    color: "brown",
    pattern: "solid",
    material: "leather",
    formality: "smart-casual",
    season: "all-season",
    description: "Brown leather belt",
  },
];
